#define DEVICE_DESCRIPTOR_SIZE_BYTE						18
#define CONFIG_DESCRIPTOR_SIZE_BYTE						67  // was 32
#define DEVICE_QALIFIER_SIZE_BYTE						10
#define STRING_LANG_DESCRIPTOR_SIZE_BYTE				4
#define STRING_MANUFACTURING_DESCRIPTOR_SIZE_BYTE		10
#define STRING_PRODUCT_DESCRIPTOR_SIZE_BYTE				20
#define STRING_SERIAL_DESCRIPTOR_SIZE_BYTE				18

typedef unsigned char uint8_t;
